rancher-sandbox/docs.rancherdesktop.io

- docs/installation.md
- docs/preferences.md
Signed-off-by: Billy Tat <btat@suse.com>
> Add note on container runtime

- .gitignore
- docs/faq.md
Works for other linux distros as well.
Addresses https://github.com/rancher-sandbox/rancher-desktop/issues/1156
> How to deal with permission problems when running docker on Ubuntu/WSL

- docs/faq.md
This started with a missing "to", but figured the text on Kim should be updated for 1.0 at the same time.
> Fix typo and update status on kim

- docs/faq.md
Added to FAQs as part of [Rancher v. RD issue](https://github.com/rancher-sandbox/rancher-desktop/issues/1342) as per Slack inquiry into Cluster Manager availability in RD.
Reference page: https://docs.rancherdesktop.io/faq
> Added note to FAQs about CM in Rancher vs. RD

- docs/faq.md
Closes [#640](https://github.com/rancher-sandbox/rancher-desktop/issues/640)
> Added additional FAQs

- docs/faq.md
Closes [#896](https://github.com/rancher-sandbox/rancher-desktop/issues/896).
> Added an FAQ for enabling the Traefik Dashboard

- docs/faq.md
> Added FAQ on mounting volumes to VMs

- docs/tutorials/hello-world-example.md
- sidebars.js
Closes [#1310](https://github.com/rancher-sandbox/rancher-desktop/issues/1310).
> Hello world example

- sidebars.js
> collapsed How-to-Guides item in the side nav menu

- docs/tutorials/hello-world-example.md
> Modified the hello world sample page to simplify the examples

- docs/how-to-guides/working-with-images.md
Added note for locally-built images.
Reference: [#31](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/31#discussion_r820024164)
> Added note about latest tag

- assets/express-sample/manifests.yaml
> Added manifests.yml to the express-sample app folder

- docs/getting-started/introduction.md
This is a common question. It's worth providing an answer.
> Adding text on Rancher vs Rancher Desktop.

- docs/how-to-guides/skaffold-and-rancher-desktop.md
- sidebars.js
Reference: [New How-to Guide](https://docs.rancherdesktop.io/how-to-guides/skaffold-and-rancher-desktop)
> Documented using Skaffold with RD

- docs/references/rdctl-command-reference.md
- sidebars.js
> Added rdctl command reference doc

- docs/how-to-guides/setup-NGINX-Ingress-Controller.md
- sidebars.js
> Added a doc page for NGINX Ingress controller setup

- docs/getting-started/features.md
> Updated Features page with Enable Kubernetes, Traefik functionality

- docs/how-to-guides/create-multi-node-cluster.md
- sidebars.js
> Added a doc with instructions to create a multi-node cluster using k3d

- docs/references/rdctl-command-reference.md
> Fixed the incorrect command example

- docs/how-to-guides/hello-world-example.md
> Made some improvements to hello world example based on user feedback

- docs/how-to-guides/rancher-on-rancher-desktop.md
> updated cert-manager version

- docs/references/rdctl-command-reference.md
> Fixed wrong syntax for rdctl --kubernetes-enables

- docs/tutorials/working-with-images.md
- Taken from [#33](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/33) with feedback from RD team.
> Updating k8s.io namespace details

- docs/getting-started/features.md
Closes https://github.com/rancher-sandbox/rancher-desktop/issues/2140 (not sure if this will do it automatically since it is cross-repo).
> Update supporting utilities section on features docs

- docs/how-to-guides/windows-provisioning-scripts.md
- sidebars.js
> Added instructions on Windows provisioning scripts

- docs/faq.md
> Updates to FAQs to reflect recent improvements/fixes

- docs/references/rdctl-command-reference.md
> Added rdctl command descriptions

- docs/faq.md
> Added a faq item for the container volume paths information

- docs/faq.md
> Added a faq item about WSL Integration

- docs/faq.md
> Removed the unintentional merge conflict text that made it to the main branch with the previous PR (troubleshooting-tips)

- docusaurus.config.js
Signed-off-by: Billy Tat <btat@suse.com>
Closes https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/83
> Update top nav bar link to RD GitHub

- docs/getting-started/installation.md
Fix the command for adding a user to a group
> Fix command example for adding user to a group in linux

- docs/getting-started/features.md
Signed-off-by: Billy Tat <btat@suse.com>
> Fix incorrect links

- docs/tutorials/working-with-containers.md
> Fixed port number typo

- docs/how-to-guides/running-air-gapped.md
- sidebars.js
This is a first draft. I can continue to work on it, or happy to hand it over to anyone on the docs team.
> Document RD when air-gapped.

- docs/how-to-guides/running-air-gapped.md
> Add the missing directory component.

- docs/faq.md
> Added an alternative way to enable traefik dashboard

- docs/how-to-guides/hello-world-example.md
> Added verbose instructions to create a Dockerfile

- docs/getting-started/installation.md
> Added a note about the Non-Admin installation on Windows

- docs/how-to-guides/skaffold-and-rancher-desktop.md
While running the how to guide I realised that a simple missing instruction could improve it.
> Adding missing instruction for running skaffold

- docs/troubleshooting-tips.md
> Added a Troubleshooting tip for the ip address conflict error

- docusaurus.config.js
- i18n/zh/code.json
- i18n/zh/docusaurus-plugin-content-docs/current.json
- i18n/zh/docusaurus-plugin-content-docs/current/faq.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/features.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/introduction.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/create-multi-node-cluster.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/hello-world-example.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/provisioning-scripts.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/running-air-gapped.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/setup-NGINX-Ingress-Controller.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/skaffold-and-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/vs-code-docker.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/vs-code-remote-containers.md
- i18n/zh/docusaurus-plugin-content-docs/current/references/architecture.md
- i18n/zh/docusaurus-plugin-content-docs/current/references/rdctl-command-reference.md
- i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting-tips.md
- i18n/zh/docusaurus-plugin-content-docs/current/tutorials/working-with-containers.md
- i18n/zh/docusaurus-plugin-content-docs/current/tutorials/working-with-images.md
- i18n/zh/docusaurus-theme-classic/footer.json
- i18n/zh/docusaurus-theme-classic/navbar.json
- package.json
- yarn.lock
This PR also upgrades Docusaurus to 2.1.0, as it has better support for multi-language settings
> Adds i18n settings and Chinese docs

- docs/getting-started/features.md
Signed-off-by: Eric Promislow <epromislow@suse.com>
> Fix typo: s/Factor Reset/Factory Reset/

- docs/how-to-guides/running-air-gapped.md
Created a local PR for PR #108 because the original writer wasn't acting on it.
The PR needed to be rebased, and there were typos and stylistic issues as well. It seemed faster to just recreate a PR from his.
> Redo PR: Update running-air-gapped.md for MS Windows installation

- docs/dependency-versions/v1.6.1.md
- docs/references/dependency-versions.md
> Updated the dependency versions doc for the 1.6.2 patch release

- docs/getting-started/installation.md
For the next version, we'll be directing the users to using the MSI package rather than the EXE installer.
> Getting-started: Describe MSI installer on Windows.

- i18n/zh/docusaurus-plugin-content-docs/current/dependency-versions/v1.6.0.md
- i18n/zh/docusaurus-plugin-content-docs/current/faq.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/running-air-gapped.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/transfer-container-images.md
- i18n/zh/docusaurus-plugin-content-docs/current/references/bundled-utilities.md
- i18n/zh/docusaurus-plugin-content-docs/current/references/rdctl-command-reference.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/diagnostics.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/general.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/images.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/port-forwarding.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/preferences/application.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/preferences/container-engine.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/preferences/kubernetes.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/preferences/virtual-machine.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/preferences/wsl.md
- i18n/zh/docusaurus-plugin-content-docs/current/ui/troubleshooting.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.6.json
- i18n/zh/docusaurus-plugin-content-docs/version-1.6/getting-started/features.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.6/how-to-guides/running-air-gapped.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest.json
- i18n/zh/docusaurus-plugin-content-docs/version-latest/getting-started/features.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/how-to-guides/running-air-gapped.md
Update Chinese translation for all versions, including 
- v1.6
- latest
- next
> Update Chinese translation for all versions

- docs/how-to-guides/create-multi-node-cluster.md
- docs/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/create-multi-node-cluster.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.6/how-to-guides/create-multi-node-cluster.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.6/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/how-to-guides/create-multi-node-cluster.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.6/how-to-guides/create-multi-node-cluster.md
- versioned_docs/version-1.6/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-latest/how-to-guides/create-multi-node-cluster.md
- versioned_docs/version-latest/how-to-guides/rancher-on-rancher-desktop.md
> Updated ranchermanager, k3s docs sites urls with the latest ones

- docs/faq.md
- docs/troubleshooting-tips.md
> Added FAQ, Troubleshooting Tip items for the app downgrade use case

- docs/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.6/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.7/how-to-guides/rancher-on-rancher-desktop.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.6/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.7/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-latest/how-to-guides/rancher-on-rancher-desktop.md
> Modified the command to always restart the container

- i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/provisioning-scripts.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.7/how-to-guides/provisioning-scripts.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/faq.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/how-to-guides/provisioning-scripts.md
Signed-off-by: vickyhella <vickyhella@hotmail.com>
> Update Chinese translation

- versioned_docs/version-latest/ui/preferences/application.md
Reverts rancher-sandbox/docs.rancherdesktop.io#162
> Revert "Document auto-start and background behavior settings"

- versioned_docs/version-1.6/how-to-guides/hello-world-example.md
- versioned_docs/version-1.7/how-to-guides/hello-world-example.md
- versioned_docs/version-1.8/how-to-guides/hello-world-example.md
- versioned_docs/version-latest/how-to-guides/hello-world-example.md
Updating the latest, 1.8, 1.7, and 1.6 versions Hello World examples with updated commands to match PR #170 .
> Updating the latest, 1.8, 1.7, and 1.6 versions Hello World Examples

- docs/bundled-utilities-version-info/v1.9.0-tech-preview.md
- docs/references/bundled-utilities.md
Updating the bundled utilities for v1.9.0-tech-preview. This PR resolves #196
> Updating the bundled utilities for v1.9.0-tech-preview

- docs/ui/extensions.md
- sidebars.js
Initial commit outlining extensions structure/layout for the UI section.
> Adding Extensions into UI Section

- docs/how-to-guides/installing-uninstalling-extensions.md
- sidebars.js
Initial commit with structure and updating sidebar showing new how-to page for extensions.
> Feature-HowTo-Extensions

- docs/ui/diagnostics.md
- docs/ui/general.md
- docs/ui/images.md
- docs/ui/port-forwarding.md
- docs/ui/preferences/application.md
- docs/ui/preferences/container-engine.md
- docs/ui/preferences/kubernetes.md
- docs/ui/preferences/virtual-machine.md
- docs/ui/preferences/wsl.md
- docs/ui/troubleshooting.md
Updating the images to point to 1.9-tech-preview S3 bucket.
> Updating the UI/Preferences Images to 1.9-tech-preview

- docs/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.6/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.7/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.8/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.9-tech-preview/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-latest/how-to-guides/rancher-on-rancher-desktop.md
This PR applies changes from PR #204  across all versions to bring the helm installation up to date for the how to guide on installing Rancher Dashboard on Rancher Desktop.
> Apply CRD Step - Rancher on Rancher Helm Install

- versioned_docs/version-latest/getting-started/installation.md
- current installation does not show latest tag, as such tech preview is being shown first to user
> update installation.md on installation to latest tag

- docs/ui/preferences/virtual-machine/emulation.md
- docs/ui/preferences/virtual-machine/hardware.md
- docs/ui/preferences/virtual-machine/network.md
- docs/ui/preferences/virtual-machine/volumes.md
- versioned_docs/version-1.9/ui/preferences/virtual-machine/emulation.md
- versioned_docs/version-1.9/ui/preferences/virtual-machine/hardware.md
- versioned_docs/version-1.9/ui/preferences/virtual-machine/network.md
- versioned_docs/version-1.9/ui/preferences/virtual-machine/volumes.md
Adding descriptions and screenshots from issues to new Virtual Machine tabs (Emulation, Hardware, Network, Volumes). Will have final screenshots uploaded in subsequent PR but included what will be the S3 URL links in this PR as placeholders. This is tied to [4635](https://github.com/rancher-sandbox/rancher-desktop/issues/4635).
> v1.9 VM Tabs - Emulation, Hardware, Network, Volumes

- i18n/zh/docusaurus-theme-classic/footer.json
Updating Chinese version copyright. Should investigate way to dynamically set this and fixes [231](https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/231).
> Updating Copyright

- docs/getting-started/deployment.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/deployment.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.9/getting-started/deployment.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/getting-started/deployment.md
- versioned_docs/version-1.9/getting-started/deployment.md
Updating deployment profile Windows locations for next, 1.9, and relevant Chinese versions.
> Update Deployment Profile Windows Locations

- docusaurus.config.js
Adding backlink to rancher.com as to align project navigation bars and per issue 235. This fixes #235 .
> Add Backlink to Nav Bar

- docs/bundled-utilities-version-info/v1.9.1.md
- docs/references/bundled-utilities.md
- versioned_docs/version-1.9/bundled-utilities-version-info/v1.9.1.md
- versioned_docs/version-1.9/references/bundled-utilities.md
- versioned_docs/version-latest/bundled-utilities-version-info/v1.9.1.md
- versioned_docs/version-latest/references/bundled-utilities.md
Adding in new section for bundled utilities v1.9.1.
> Bundled Utilities 1.9.1

- docs/getting-started/introduction.md
- versioned_docs/version-1.9/getting-started/introduction.md
- versioned_docs/version-latest/getting-started/introduction.md
Updating the intro screenshots with latest versions of Kubernetes settings. This fixes #175 .
> Update Introduction Screenshots

- i18n/zh/docusaurus-plugin-content-docs/current/bundled-utilities-version-info/v1.9.1.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/introduction.md
- i18n/zh/docusaurus-plugin-content-docs/current/references/bundled-utilities.md
- i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting-tips.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.9/bundled-utilities-version-info/v1.9.1.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.9/getting-started/introduction.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.9/references/bundled-utilities.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.9/troubleshooting-tips.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/bundled-utilities-version-info/v1.9.1.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/getting-started/introduction.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/references/bundled-utilities.md
- i18n/zh/docusaurus-plugin-content-docs/version-latest/troubleshooting-tips.md
Update Chinese docs for all versions
> Update Chinese docs

- docs/ui/diagnostics.md
- docs/ui/extensions.md
- docs/ui/general.md
- docs/ui/images.md
- docs/ui/port-forwarding.md
- docs/ui/troubleshooting.md
- versioned_docs/version-1.7/ui/diagnostics.md
- versioned_docs/version-1.7/ui/general.md
- versioned_docs/version-1.7/ui/images.md
- versioned_docs/version-1.7/ui/port-forwarding.md
- versioned_docs/version-1.7/ui/troubleshooting.md
- versioned_docs/version-1.8/ui/diagnostics.md
- versioned_docs/version-1.8/ui/general.md
- versioned_docs/version-1.8/ui/images.md
- versioned_docs/version-1.8/ui/port-forwarding.md
- versioned_docs/version-1.8/ui/troubleshooting.md
- versioned_docs/version-1.9/ui/diagnostics.md
- versioned_docs/version-1.9/ui/extensions.md
- versioned_docs/version-1.9/ui/general.md
- versioned_docs/version-1.9/ui/images.md
- versioned_docs/version-1.9/ui/port-forwarding.md
- versioned_docs/version-1.9/ui/troubleshooting.md
Adding canonical links to UI section (General, PF, Images, Diagnostics, Extensions, Troubleshooting).
> Add Canonical Links Pt 7

- docs/getting-started/deployment.md
- docs/how-to-guides/installing-uninstalling-extensions.md
- docs/ui/diagnostics.md
- docs/ui/extensions.md
- docs/ui/general.md
- docs/ui/images.md
- docs/ui/port-forwarding.md
- docs/ui/preferences/application/behavior.md
- docs/ui/preferences/application/environment.md
- docs/ui/preferences/application/general.md
- docs/ui/preferences/container-engine/allowed-images.md
- docs/ui/preferences/container-engine/general.md
- docs/ui/preferences/kubernetes.md
- docs/ui/preferences/virtual-machine/emulation.md
- docs/ui/preferences/virtual-machine/hardware.md
- docs/ui/preferences/virtual-machine/network.md
- docs/ui/preferences/virtual-machine/volumes.md
- docs/ui/preferences/wsl/integrations.md
- docs/ui/preferences/wsl/network.md
- docs/ui/preferences/wsl/proxy.md
- docs/ui/troubleshooting.md
Updating the image screenshot links to point to the 1.10 Rancher Desktop URL for the S3 bucket suse-rancher-media.
> Updating RD 1.10 Screenshots URL

- docs/bundled-utilities-version-info/v1.10.0.md
- docs/references/bundled-utilities.md
Updating the bundled utilities page and reference folder with 1.10 utilities.
> Updating Bundled Utilities 1.10

- docs/faq.md
- versioned_docs/version-1.9/faq.md
- versioned_docs/version-latest/faq.md
Removing FAQ section on manually adding RD to Windows startup that has been fixed by a [UI configuration](https://docs.rancherdesktop.io/ui/preferences/application/behavior/#startup) to allow RD on the Windows startup program list. This fixes #276 .
> Remove Obsolete FAQ

- static/robots.txt
Adding robots.txt file to help with SEO and file crawling for documentation.
> Add robots.txt File

- docs/ui/preferences/virtual-machine/emulation.md
- versioned_docs/version-1.10/ui/preferences/virtual-machine/emulation.md
- versioned_docs/version-latest/ui/preferences/virtual-machine/emulation.md
Updating emulation page formatting and style.
> Emulation Page Update

- docs/how-to-guides/provisioning-scripts.md
- versioned_docs/version-1.10/how-to-guides/provisioning-scripts.md
- versioned_docs/version-latest/how-to-guides/provisioning-scripts.md
Updating provisioning page with added step/note for _config directory for macOS/Linux, and adding note to Windows section. From slack discussion https://rancher-users.slack.com/archives/C0200L1N1MM/p1695119358222119
> Provisioning Page Update

- .github/workflows/test-deploy.yml
- docs/how-to-guides/rancher-on-rancher-desktop.md
- docs/ui/images.md
- package.json
- versioned_docs/version-1.10/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.10/ui/images.md
- versioned_docs/version-1.6/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.7/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.7/ui/images.md
- versioned_docs/version-1.8/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.8/ui/images.md
- versioned_docs/version-1.9-tech-preview/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.9-tech-preview/ui/images.md
- versioned_docs/version-1.9/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.9/ui/images.md
- versioned_docs/version-latest/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-latest/ui/images.md
- yarn.lock
This PR: 
- Adds a link checking step to the `test-deploy` action. The `--frail` option has been included and will cause the `test-deploy` step to fail if a PR introduces broken links. This can be removed if we want to be less strict.
- Fixes existing broken links inn the `en` doc set.
> Add link checker

- docs/ui/preferences/wsl/proxy.md
- versioned_docs/version-1.10/ui/preferences/wsl/proxy.md
- versioned_docs/version-latest/ui/preferences/wsl/proxy.md
Updating the Windows Proxy page with a known issue section on wsl-vpnkit and Rancher Desktop. This fixes #292 .
> WSL Known Issues `wsl-vpnkit`

- docs/ui/extensions.md
- versioned_docs/version-1.10/ui/extensions.md
- versioned_docs/version-latest/ui/extensions.md
Updating extensions page with section on debugging extensions with a link to instructions. This fixes #263 .
> Update Extensions Page - Remote Debugging

- docusaurus.config.js
Updating the header and footer for Rancher Desktop to the standard across projects for SUSE Rancher.
> Revised Rancher Desktop Header/Footer

- docs/how-to-guides/traefik-ingress-example.md
- versioned_docs/version-1.10/how-to-guides/traefik-ingress-example.md
- versioned_docs/version-latest/how-to-guides/traefik-ingress-example.md
Adding updated command setting the IP variable if a user has socket-vmnet enabled for their macOS network.
> Updating Traefik How-to - IP Variable with socket-vmnet

- docs/bundled-utilities-version-info/v1.11.0.md
- docs/how-to-guides/generating-deployment-profiles.md
- docs/references/bundled-utilities.md
- sidebars.js
Adding the updated bundled utilities and bringing in the sidebars/formatting changes in this PR to keep the images PR separate.
> Updating Bundled Utilities and Formatting Generating Deployment Profiles

- docs/ui/images.md
- versioned_docs/version-1.11/ui/images.md
- versioned_docs/version-latest/ui/images.md
Revising the Images tab with summary of management options based on container engine used. Also updated some wording with Scanning Images and Adding Images steps. Fixes #299 .
> Revise Images Page

- docs/faq.md
- versioned_docs/version-1.11/faq.md
- versioned_docs/version-latest/faq.md
Updating the FAQ with step on shutting down WSL before downgrading for Windows users. Fixes #323
> Update FAQ - WSL shutdown

- docs/ui/containers.md
Adding updated language for Containers page and the namespace selector field when using the containerd engine.
Fixes #327.
> Updating Containers Page - Namespace Selector

- versioned_docs/version-1.12/getting-started/deployment.md
- versioned_docs/version-latest/getting-started/deployment.md
Syncing the `deployment.md` pages after version field update for RD 1.12.
> Syncing Deployment Pages - RD 1.12

- versioned_docs/version-1.12/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
Syncing the latest versions with updated proxy whitelist.
> Syncing Installation Page - Latest/1.12 Versions

- docs/getting-started/deployment.md
- docs/getting-started/introduction.md
- docs/how-to-guides/installing-uninstalling-extensions.md
- docs/ui/extensions.md
- versioned_docs/version-1.12/getting-started/deployment.md
- versioned_docs/version-1.12/getting-started/introduction.md
- versioned_docs/version-1.12/how-to-guides/installing-uninstalling-extensions.md
- versioned_docs/version-1.12/ui/extensions.md
- versioned_docs/version-latest/getting-started/deployment.md
- versioned_docs/version-latest/getting-started/introduction.md
- versioned_docs/version-latest/how-to-guides/installing-uninstalling-extensions.md
- versioned_docs/version-latest/ui/extensions.md
Adding the introduction screenshot for the latest 1.12 version, syncing Windows screenshots across versions and also a minor spelling revision.
Fixes #332.
> Updating Introduction/Windows Screenshots - Syncing Versions

- docs/bundled-utilities-version-info/v1.13.0.md
- docs/references/bundled-utilities.md
- docs/tutorials/working-with-webassembly.md
- docs/ui/preferences/container-engine/general.md
- docusaurus.config.js
- sidebars.js
* Added version information for bundled utilities
* Added WASM tutorial and WASM info to Containers > General page
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/6554
> Update docs for 1.13.0 release

- docs/faq.md
- docs/how-to-guides/generating-deployment-profiles.md
- docs/how-to-guides/mirror-private-registry.md
- docs/how-to-guides/provisioning-scripts.md
- docs/how-to-guides/traefik-ingress-example.md
- docs/how-to-guides/using-testcontainers.md
- docs/ui/port-forwarding.md
- docs/ui/preferences/application/general.md
- docs/ui/preferences/virtual-machine/network.md
- docs/ui/snapshots.md
- versioned_docs/version-1.13/faq.md
- versioned_docs/version-1.13/how-to-guides/generating-deployment-profiles.md
- versioned_docs/version-1.13/how-to-guides/mirror-private-registry.md
- versioned_docs/version-1.13/how-to-guides/traefik-ingress-example.md
- versioned_docs/version-1.13/how-to-guides/using-testcontainers.md
- versioned_docs/version-1.13/ui/port-forwarding.md
- versioned_docs/version-1.13/ui/preferences/application/general.md
- versioned_docs/version-1.13/ui/preferences/virtual-machine/network.md
- versioned_docs/version-1.13/ui/snapshots.md
- versioned_docs/version-latest/faq.md
- versioned_docs/version-latest/how-to-guides/generating-deployment-profiles.md
- versioned_docs/version-latest/how-to-guides/mirror-private-registry.md
- versioned_docs/version-latest/how-to-guides/traefik-ingress-example.md
- versioned_docs/version-latest/how-to-guides/using-testcontainers.md
- versioned_docs/version-latest/ui/port-forwarding.md
- versioned_docs/version-latest/ui/preferences/application/general.md
- versioned_docs/version-latest/ui/preferences/virtual-machine/network.md
- versioned_docs/version-latest/ui/snapshots.md
Updating links to relative links in the latest version docs and /next/. Also made some spelling corrections in related pages.
Fixes https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/346.
> Update Links to Relative Links - Latest/Next Versions

- .github/workflows/deploy.yml
Reverts rancher-sandbox/docs.rancherdesktop.io#367
> Revert "Updated the deploy GitHub action"

- docs/getting-started/deployment.md
- docs/getting-started/introduction.md
- docs/how-to-guides/installing-uninstalling-extensions.md
- docs/ui/containers.md
- docs/ui/diagnostics.md
- docs/ui/extensions.md
- docs/ui/general.md
- docs/ui/images.md
- docs/ui/port-forwarding.md
- docs/ui/preferences/application/behavior.md
- docs/ui/preferences/application/environment.md
- docs/ui/preferences/application/general.md
- docs/ui/preferences/container-engine/allowed-images.md
- docs/ui/preferences/container-engine/general.md
- docs/ui/preferences/kubernetes.md
- docs/ui/preferences/virtual-machine/emulation.md
- docs/ui/preferences/virtual-machine/hardware.md
- docs/ui/preferences/virtual-machine/network.md
- docs/ui/preferences/virtual-machine/volumes.md
- docs/ui/preferences/wsl/integrations.md
- docs/ui/preferences/wsl/network.md
- docs/ui/preferences/wsl/proxy.md
- docs/ui/snapshots.md
- docs/ui/troubleshooting.md
```shell
find docs -name '*.md' -exec perl -p -i -e 's#/v1\.13/(.*\.png)#/v1.14/$1#' {} \;
```
> Bump screenshot URLs from 1.13 to 1.14

- sidebars.js
> VM preferences sidebar should follow window tab order

- docs/getting-started/installation.md
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/6390
> Document that latest Windows 2022 Server is also supported

- src/css/custom.css
> Don't hardcode img classname in CSS

- docs/getting-started/installation.md
- versioned_docs/version-1.17/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
We no longer attempt to install WSL from within our own installer.  Update the documentation to describe this.
> Install: the user must now manually install WSL first

- versioned_docs/version-latest/getting-started/installation.md
Update requirement section format in installation.md
The Bold format should be correct to work with markdown
> Update requirement section format in installation.md

- docs/getting-started/installation.md
- versioned_docs/version-1.18/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
> Rancher Desktop needs macOS 13 (Ventura) or later

- docs/ui/volumes.md
- sidebars.js
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/9009
> Add Volumes page documentation

- docs/references/rdctl-command-reference.md
- versioned_docs/version-1.10/references/rdctl-command-reference.md
- versioned_docs/version-1.11/references/rdctl-command-reference.md
- versioned_docs/version-1.9-tech-preview/references/rdctl-command-reference.md
- versioned_docs/version-1.9/references/rdctl-command-reference.md
(also fixes some local file references in ancient docs)
> Update rdctl reference for 1.20.0
