- docs/faq.md
Addressing issue when calling kubectl from console on Ubuntu returns `kubectl: command not found`- Rancher Desktop 1.0.0-beta.1 installed from deb package.
> FAQ: Add `kubectl: command not found` instructions

- docs/faq.md
➜  ~ kubectl config use-context rancher-desktop
Switched to context "rancher-desktop".
➜  ~ kubectl delete node lima rancher-desktop
Error from server (NotFound): nodes "lima" not found
Error from server (NotFound): nodes "rancher-desktop" not found
➜  ~ kubectl delete node lima-rancher-desktop
node "lima-rancher-desktop" deleted
> Fix command for workaround for disabling Kubernetes

- docs/faq.md
The instructions currently use `sudo addgrp docker`, where `addgrp` is not a valid command
> Docs: Fix incorrect groupadd command

- docs/installation.md
[This issue][issue] is caused by the user not having sufficient permissions to access `/dev/kvm`. On other tested distributions there is no problem because the user has the needed permissions on `/dev/kvm` via either file ACLs or SELinux policies. The only solution I am aware of is to add another (simple) step to documentation, which is what this PR does.
[issue]: https://github.com/rancher-sandbox/rancher-desktop/issues/1344
> Add docs to get around kvm permissions issue

- docs/installation.md
> Update docs to not use deprecated `apt-key`

- docs/getting-started/installation.md
Closes #80.
Also fixes a typo: the installation docs said that `docker-compose` is only included when we are using the docker runtime. This is not true - it is always included. Also, `nerdctl` can use it via `nerdctl compose`.
Note that this should not be merged until 1.4 is released, since it describes features that will only be present in 1.4.
> Document setup for `docker-credential-pass` on Linux

- docs/tutorials/working-with-containers.md
Add some additional documentation about exposing ports to all network interfaces on windows.
Fixes: #76 
Also removed some out of place code samples in the "Exposing a Port" section that were building a container.
> Document Windows port exposing workaround

- docs/how-to-guides/vs-code-remote-containers.md
> Typo in How-to Guides > VS Code Remote Containers

- docusaurus.config.js
- sidebars.js
The sidebar starts now fully collapsed except for `Getting started` category, and only one category can be expanded while the others are automatically collapsed.
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>
> Changed sidebar behavior

- docs/ui/preferences/container-engine.md
We will likely simplify the patterns from regular expressions to simply allow '*' wildcards, so anything referencing regular expressions has been removed.
Also added a note that filtering by tag doesn't actually work.
> Simplify explanation of Allowed Images patterns

- i18n/zh/docusaurus-plugin-content-docs/version-latest.json
The translated sidebar for the `latest` version was missing `User Interface` and `Preferences`.
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>
> Added CN translations for latest sidebar

- docs/how-to-guides/provisioning-scripts.md
- versioned_docs/version-1.7/how-to-guides/provisioning-scripts.md
- versioned_docs/version-latest/how-to-guides/provisioning-scripts.md
The field `defaultValue` in the Provisioning page tabs causes a page crash on Windows machines as the Tabs only have MacOS and Linux.
The option was removed and the page is displayed correctly.
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>
> Removed defaultValue from Tabs

- docs/ui/port-forwarding.md
- docs/ui/preferences/container-engine.md
- versioned_docs/version-1.7/ui/port-forwarding.md
- versioned_docs/version-1.7/ui/preferences/container-engine.md
- versioned_docs/version-latest/ui/port-forwarding.md
- versioned_docs/version-latest/ui/preferences/container-engine.md
In the sidebar, updated the capitalization from "Port forwarding" to "Port Forwarding" and "Container engine" to "Container Engine" to match standard page names. This PR addresses #133 .
Signed-off-by: Sunil Singh <sunil.singh@suse.com>
> Updated the capitalization to "Port Forwarding" and "Container Engine"

- docs/faq.md
- versioned_docs/version-1.7/faq.md
With the current versioned docs approach, whenever we make an update to the released version, we need to copy over the changes at three places. 
- `versioned_docs/version-latest`  to support the links with no version number in the url
-  `versioned_docs/<current release version>` to support the version number in the url, basically to link from the application GUI
-  `docs` which is the work in progress version which will be promoted as the next release version
This is duplicating code at multiple places but we need to live with this till we come up with a better appraoch.
> Synced the recently updated faq file in the latest folder with the one in the next and the 1.7 version folders

- docs/getting-started/installation.md
- versioned_docs/version-1.6/getting-started/installation.md
- versioned_docs/version-1.7/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
Updating the installation guide for linux distributions to address Traefik port binding access and setting unprivileged ports below `1024`. This PR address #149 .
> Updating installation guide for linux users on Traefik port binding

- docs/how-to-guides/running-air-gapped.md
- versioned_docs/version-1.6/how-to-guides/running-air-gapped.md
- versioned_docs/version-1.7/how-to-guides/running-air-gapped.md
- versioned_docs/version-latest/how-to-guides/running-air-gapped.md
This update is for what users should expect to download for their respective source disk `k3s` compressed tarball when preparing for an air-gapped system. Also some markdown cleanup across the files.
> Updating Running When Offline Documentation

- docusaurus.config.js
- package.json
- yarn.lock
This PR enables Google Analytics through [Google Tag Manager](https://marketingplatform.google.com/about/tag-manager/) as part of an effort by the Docs team to better understand how users use our docs. 
Please connect with @gunamata for details and access to data/dashboards when available.
Note that Docusaurus is bumped to v2.3.1 in order to use the `plugin-google-tag-manager` plugin that becomes available as part of the [presets](https://docusaurus.io/docs/using-plugins#using-presets).
> Enable analytics

- versioned_docs/version-latest/ui/preferences/application.md
The old "Behavior" tab is now called "General", and the new options are configurable on the second tab called "Behavior".
The documentation for the new Behavior tab has been duplicated from Windows to macOS and Linux. The macOS verbiage has been slightly adjusted to use OS-specific terms, like "app switcher" and "dock" instead of "task switcher" and "task bar". It also adds "in the menu bar" to "notification icon" because the concept is normally known as the "menu bar icon" on macOS.
The Linux version still uses Windows terminology; not sure if there is native terminology that is consistent across window managers.
This commit also moves the screenshots to the top of the section describing the individual settings.
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/3775
> Document auto-start and background behavior settings

- docs/ui/diagnostics.md
- docs/ui/port-forwarding.md
- docs/ui/preferences/container-engine.md
- docs/ui/preferences/kubernetes.md
- docs/ui/preferences/virtual-machine.md
- docs/ui/troubleshooting.md
In manuals you want to see the illustration first, and then read the description of the elements in the image. The general structure should be:
* introduction/overview
* screenshot
* detailed description of each element in the screenshot
This commit only moves text around, but doesn't change any.
It also normalizes some of the headings (for Preferences only):
Tab names are level 3 headings
Settings labels are level 4 headings
> Move screenshots before their descriptions

- docs/how-to-guides/hello-world-example.md
Not sure why the examples do this, but it makes no sense to me. And if you are in your `HOME` directory, then this won't even work:
```console
$ mkdir ../hello-world
mkdir: ../hello-world: Permission denied
```
This change should be applied to latest and older docs as well.
> Don't create sample directories in the parent dir

- docs/references/rdctl-command-reference.md
- scripts/update-codeblocks
This PR adds a script to re-run commands in code blocks inside the documentation to update their output using the latest version of the commands (usually `rdctl`).
It is best reviewed commit-by-commit:
1. Add `update-codeblocks` script
2. Annotate `rdctl-command-reference.md` with `autoupdate=true` attributes
3. Run `./scripts/update-codeblocks --update docs/references/rdctl-command-reference.md`
The tools is just an initial experiment. It doesn't handle errors/STDERR in the command output correctly in all cases.
It may also need to be rewritten in e.g. Ruby because the rest of the Rancher Desktop team is not really comfortable maintaining Perl scripts (but maybe the docs team is?).
Fixes #173
> Automate updating rdctl sample command output

- docs/references/rdctl-command-reference.md
Example code output was growing in the rdctl reference page, implemented collapsible codeblocks to mitigate this growth.
> Collapsible Codeblocks Reference Page

- docusaurus.config.js
- package.json
- yarn.lock
Updated Docusaurus from v2.3.1 to v2.4.0.
Google GTAG plugin was also enabled and configured.
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>
> Updated Docusaurus to v2.4.0

- docs/references/bundled-utilities.md
The next version bundled utilities v1.8 was missing, updated to sync up properly with all versions.
> Updating bundled utilities v1.8 for the `next` version

- docusaurus.config.js
This PR updates the tracking ID for the Google tag per Jira SD-101310. 
Context [slack thread](https://suse.slack.com/archives/C02DQMPRA1E/p1680246378430449).
> Updates GTM tracking to correct container ID

- docs/getting-started/installation.md
- versioned_docs/version-1.6/getting-started/installation.md
- versioned_docs/version-1.7/getting-started/installation.md
- versioned_docs/version-1.8/getting-started/installation.md
- versioned_docs/version-1.9-tech-preview/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
Adding back in Traefik hint to persist ports as it seems the change was lost when resyncing the latest version for the recent 1.9-tech-preview release.
> Add Back Traefik Persist Ports Hint

- docusaurus.config.js
Updating the `docusaurus.config` file to remove the banner for v1.8 docs showing "...no longer actively maintained".
> Remove Banner for v1.8

- docs/getting-started/installation.md
- versioned_docs/version-1.6/getting-started/installation.md
- versioned_docs/version-1.7/getting-started/installation.md
- versioned_docs/version-1.8/getting-started/installation.md
- versioned_docs/version-1.9-tech-preview/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
Updating the Linux header structure for the installation guide. Now, all requirements are under the requirement header and all linux install headers are at the same level. This should increase readability for users needing to install through Linux as the scroll bar to the right has standardized sections now. This PR fixes #176 .
> Updating the Linux Header Structure in Install Guide

- docs/troubleshooting-tips.md
- versioned_docs/version-1.8/troubleshooting-tips.md
- versioned_docs/version-latest/troubleshooting-tips.md
Adding a troubleshooting tip for users seeing a Docker error when starting a container in VS code using the dev-containers extension >v0.266. This is tied to [4436](https://github.com/rancher-sandbox/rancher-desktop/issues/4436) on RD.
> Troubleshooting Tip Dev-Containers

- docusaurus.config.js
Updating the top nav bar to have a dropdown labeled Quick Links that holds the RD Home, RD GitHub, and RD Docs GitHub links so as to synthesize/organize top level links.
> Update Top Navbar with Quick Links

- docs/ui/preferences/wsl/integrations.md
- docs/ui/preferences/wsl/proxy.md
- sidebars.js
- versioned_docs/version-1.9/ui/preferences/wsl/integrations.md
- versioned_docs/version-1.9/ui/preferences/wsl/proxy.md
- versioned_sidebars/version-1.9-sidebars.json
Adding the proxy page skeleton and updating the sidebars. Additionally updating the integrations page to remove redundancy as the integrations page is only present on the WSL tab. This is tied to [issue 4719](https://github.com/rancher-sandbox/rancher-desktop/issues/4719).
> WSL - Proxy and Integrations Page Update 

- .github/workflows/deploy.yml
- .github/workflows/test-deploy.yml
The following warning is found in the Summary tab of each run of an action using Node.js 12. E.g. https://github.com/rancher-sandbox/docs.rancherdesktop.io/actions/runs/5081746810.
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Bump deprecated Node.js actions

- docs/getting-started/deployment.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/deployment.md
- i18n/zh/docusaurus-plugin-content-docs/version-1.9/getting-started/deployment.md
- versioned_docs/version-1.9/getting-started/deployment.md
Updating the location of deployment profiles for the docs versions `next`/`1.9` to `HKLM\Software\Policies\Rancher Desktop` and `HKCU\Software\Policies\Rancher Desktop`, respectively. This work is tied to [issue 4518](https://github.com/rancher-sandbox/rancher-desktop/issues/4518).
> Update Deployment Profile - Location

- docs/getting-started/deployment.md
- versioned_docs/version-1.9/getting-started/deployment.md
Updating the deployment profile page with the locked field feature available for all preference fields. This added section is for v1.9 and also updated the headers to title case. This is tied to [issue 4662](https://github.com/rancher-sandbox/rancher-desktop/issues/4662).
> Update Deployment Profile - Locked Fields

- docs/ui/port-forwarding.md
- versioned_docs/version-1.9/ui/port-forwarding.md
Updating the port forward page with section on port mappings for admin vs non-admin installations, and updated the headers to improve readability. This addresses [issue 4296](https://github.com/rancher-sandbox/rancher-desktop/issues/4296).
> Update Port Forward - Port Mappings

- docs/ui/preferences/wsl/integrations.md
- docs/ui/preferences/wsl/network.md
- versioned_docs/version-1.9/ui/preferences/wsl/integrations.md
- versioned_docs/version-1.9/ui/preferences/wsl/network.md
Adding screenshots and descriptions for Network and Integrations tab. Screenshots will be updated in S3 once updated screenshots are received but URL addresses should remain unchanged. This is tied to [4719](https://github.com/rancher-sandbox/rancher-desktop/issues/4719) and [4635](https://github.com/rancher-sandbox/rancher-desktop/issues/4635).
> V1.9 WSL Tabs - Integrations, Networking

- docs/getting-started/deployment.md
- docs/getting-started/installation.md
- docs/getting-started/introduction.md
- docs/tutorials/working-with-containers.md
- docs/tutorials/working-with-images.md
- versioned_docs/version-1.6/getting-started/installation.md
- versioned_docs/version-1.6/getting-started/introduction.md
- versioned_docs/version-1.6/tutorials/working-with-containers.md
- versioned_docs/version-1.6/tutorials/working-with-images.md
- versioned_docs/version-1.7/getting-started/installation.md
- versioned_docs/version-1.7/getting-started/introduction.md
- versioned_docs/version-1.7/tutorials/working-with-containers.md
- versioned_docs/version-1.7/tutorials/working-with-images.md
- versioned_docs/version-1.8/getting-started/deployment.md
- versioned_docs/version-1.8/getting-started/installation.md
- versioned_docs/version-1.8/getting-started/introduction.md
- versioned_docs/version-1.8/tutorials/working-with-containers.md
- versioned_docs/version-1.8/tutorials/working-with-images.md
- versioned_docs/version-1.9/getting-started/deployment.md
- versioned_docs/version-1.9/getting-started/installation.md
- versioned_docs/version-1.9/getting-started/introduction.md
- versioned_docs/version-1.9/tutorials/working-with-containers.md
- versioned_docs/version-1.9/tutorials/working-with-images.md
Part 2 of adding canonical links for SEO improvement with Rancher Desktop. This PR affects all pages in the Getting Started and Tutorials drop-down.
> Add Canonical Links Pt 2

- docs/how-to-guides/create-multi-node-cluster.md
- docs/how-to-guides/hello-world-example.md
- docs/how-to-guides/increasing-open-file-limit.md
- docs/how-to-guides/installing-uninstalling-extensions.md
- docs/how-to-guides/transfer-container-images.md
- versioned_docs/version-1.6/how-to-guides/create-multi-node-cluster.md
- versioned_docs/version-1.6/how-to-guides/hello-world-example.md
- versioned_docs/version-1.6/how-to-guides/increasing-open-file-limit.md
- versioned_docs/version-1.7/how-to-guides/create-multi-node-cluster.md
- versioned_docs/version-1.7/how-to-guides/hello-world-example.md
- versioned_docs/version-1.7/how-to-guides/increasing-open-file-limit.md
- versioned_docs/version-1.7/how-to-guides/transfer-container-images.md
- versioned_docs/version-1.8/how-to-guides/create-multi-node-cluster.md
- versioned_docs/version-1.8/how-to-guides/hello-world-example.md
- versioned_docs/version-1.8/how-to-guides/increasing-open-file-limit.md
- versioned_docs/version-1.8/how-to-guides/transfer-container-images.md
- versioned_docs/version-1.9/how-to-guides/create-multi-node-cluster.md
- versioned_docs/version-1.9/how-to-guides/hello-world-example.md
- versioned_docs/version-1.9/how-to-guides/increasing-open-file-limit.md
- versioned_docs/version-1.9/how-to-guides/installing-uninstalling-extensions.md
- versioned_docs/version-1.9/how-to-guides/transfer-container-images.md
Updating canonical links for how-to pages, partial amount of pages across all non-latest versions were updated to keep review manageable. This is tied to #245.
> Add Canonical Links Pt 3

- docs/how-to-guides/provisioning-scripts.md
- docs/how-to-guides/rancher-on-rancher-desktop.md
- docs/how-to-guides/running-air-gapped.md
- docs/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.6/how-to-guides/provisioning-scripts.md
- versioned_docs/version-1.6/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.6/how-to-guides/running-air-gapped.md
- versioned_docs/version-1.6/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.7/how-to-guides/provisioning-scripts.md
- versioned_docs/version-1.7/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.7/how-to-guides/running-air-gapped.md
- versioned_docs/version-1.7/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.8/how-to-guides/provisioning-scripts.md
- versioned_docs/version-1.8/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.8/how-to-guides/running-air-gapped.md
- versioned_docs/version-1.8/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.9/how-to-guides/provisioning-scripts.md
- versioned_docs/version-1.9/how-to-guides/rancher-on-rancher-desktop.md
- versioned_docs/version-1.9/how-to-guides/running-air-gapped.md
- versioned_docs/version-1.9/how-to-guides/setup-NGINX-Ingress-Controller.md
Adding canonical links to how-to section pages in Rancher Desktop. This is tied to #245.
> Add Canonical Links Pt 4

- docs/how-to-guides/skaffold-and-rancher-desktop.md
- docs/how-to-guides/vs-code-docker.md
- docs/how-to-guides/vs-code-remote-containers.md
- docs/references/architecture.md
- versioned_docs/version-1.6/how-to-guides/skaffold-and-rancher-desktop.md
- versioned_docs/version-1.6/how-to-guides/vs-code-docker.md
- versioned_docs/version-1.6/how-to-guides/vs-code-remote-containers.md
- versioned_docs/version-1.6/references/architecture.md
- versioned_docs/version-1.7/how-to-guides/skaffold-and-rancher-desktop.md
- versioned_docs/version-1.7/how-to-guides/vs-code-docker.md
- versioned_docs/version-1.7/how-to-guides/vs-code-remote-containers.md
- versioned_docs/version-1.7/references/architecture.md
- versioned_docs/version-1.8/how-to-guides/skaffold-and-rancher-desktop.md
- versioned_docs/version-1.8/how-to-guides/vs-code-docker.md
- versioned_docs/version-1.8/how-to-guides/vs-code-remote-containers.md
- versioned_docs/version-1.8/references/architecture.md
- versioned_docs/version-1.9/how-to-guides/skaffold-and-rancher-desktop.md
- versioned_docs/version-1.9/how-to-guides/vs-code-docker.md
- versioned_docs/version-1.9/how-to-guides/vs-code-remote-containers.md
- versioned_docs/version-1.9/references/architecture.md
Adding canonical links to the final pages of the how-to section and the architecture page in the references section.
> Add Canonical Links Pt 5

- docs/how-to-guides/provisioning-scripts.md
- versioned_docs/version-1.9/how-to-guides/provisioning-scripts.md
- versioned_docs/version-latest/how-to-guides/provisioning-scripts.md
Updating provisioning script page with an example on using K3S_EXEC for implementing custom settings for K3s. Also some minor formatting updates. This fixes https://github.com/rancher-sandbox/docs.rancherdesktop.io/issues/239. Converting to draft as this depends on some changes in https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/253.
> Updating Provisioning Page - K3s example

- docs/how-to-guides/odo-rancher-desktop.md
- sidebars.js
Adding a how-to guide for using [ODO](https://odo.dev/docs/introduction) and Rancher Desktop. The main examples used are the commands `odo init`, `odo dev`, and `odo deploy`. Makes use of the existing `express-sample` nodejs application in the RD docs repo.
> ODO and RD How-To

- docs/references/rdctl-command-reference.md
Updating the rdctl command reference page with new --no-modal-dialogs (https://github.com/rancher-sandbox/rancher-desktop/issues/4985) for rdctl-start and rdctl create-profile (https://github.com/rancher-sandbox/rancher-desktop/issues/5020).
> Update rdctl create-profile & --no-modal-dialogs in command reference

- docs/ui/preferences/virtual-machine/volumes.md
- versioned_docs/version-1.9/ui/preferences/virtual-machine/volumes.md
- versioned_docs/version-latest/ui/preferences/virtual-machine/volumes.md
Updating the VM | Volumes (macOS & Linux) page for 1.10 virtiofs addition to Linux, as well as changes to latest/1.9 formatting and definition link for reverse-sshfs. The image update will happen in a subsequent S3 update, but inputting the future image link URL in this PR. This is tied to https://github.com/rancher-sandbox/rancher-desktop/issues/5110.
> Updating the VM | Volumes (macOS & Linux) Page - virtiofs

- docs/references/rdctl-command-reference.md
Updating the command reference page with updated rdctl list-settings --help output. This is tied to 1.10 feature work https://github.com/rancher-sandbox/rancher-desktop/pull/5006
> Updating Command Reference Output - rdctl list-settings --help

- docs/how-to-guides/installing-uninstalling-extensions.md
- docs/ui/extensions.md
- versioned_docs/version-1.9/how-to-guides/installing-uninstalling-extensions.md
- versioned_docs/version-latest/how-to-guides/installing-uninstalling-extensions.md
This updates the Extensions | Installed tab with the `Remove` button to uninstall extensions in place of `Uninstall`. This is tied to the work in https://github.com/rancher-sandbox/rancher-desktop/issues/5069. 
The `Extensions-Installed` images will be updated in a subsequent PR for the UI/Guides sections, and  additionally updated the how-to guides across versions showing the Installed tab and appropriate `Remove` or `Uninstall` button.
> Update Extensions | Installed with Remove

- docs/references/rdctl-command-reference.md
Updating the list-settings --help with the correct output and reverting `--output` update.
> Updating rdctl list-settings with correct output

- docs/ui/preferences/wsl/proxy.md
Updating the proxy page with new field No proxy hostname list. This is tied to https://github.com/rancher-sandbox/rancher-desktop/issues/5100.
> WSL Proxy - No proxy hostname list Update

- docs/getting-started/installation.md
- versioned_docs/version-1.10/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
Updating install page Linux section with note on system tray being unavailable for certain distros, leading to RD's tray icon not being displayed. This is tied to #275.
> Linux Install Note - Tray Icon

- versioned_docs/version-1.9/ui/preferences/application/environment.md
After i install rancher desktop 1.9 in win 11, i can not find the environment under application tab, so i suppose this only shows in Mac or Linux os?
> Update environment.md 

- docs/ui/port-forwarding.md
- versioned_docs/version-1.10/ui/port-forwarding.md
- versioned_docs/version-1.9/ui/port-forwarding.md
- versioned_docs/version-latest/ui/port-forwarding.md
Fixing broken links for Traefik Port Binding Access on the Port Forwarding page. Also reviewed links for next and latest versions and did not find any other broken links. This fixes #288 .
> Fixing Broken Links - Port Forwarding

- docs/how-to-guides/using-testcontainers.md
- sidebars.js
- versioned_docs/version-1.10/how-to-guides/using-testcontainers.md
- versioned_docs/version-latest/how-to-guides/using-testcontainers.md
- versioned_sidebars/version-1.10-sidebars.json
- versioned_sidebars/version-latest-sidebars.json
Adding how-to guide for using Testcontainers on Rancher Desktop for Linux, macOS(workarounds for M1 machines included), and Windows. This fixes #282 .
> How-to Guide - Using Testcontainers

- docs/ui/preferences/wsl/proxy.md
The issue has been fixed for the upcoming 1.11 release, removing the workaround for the next version.
> Remove WSL Workaround for 1.11

- docs/references/rdctl-command-reference.md
Updating the rdctl command reference page with rdctl snapshot commands. This is tied to https://github.com/rancher-sandbox/rancher-desktop/issues/5597#event-10489909106.
> Update Command Reference - rdctl snapshot

- docs/ui/preferences/virtual-machine/network.md
Updating the macOS network page with section on `mDNSResponder` daemon and use of port 53. This fixes https://github.com/rancher-sandbox/rancher-desktop/issues/5385.
> Update macOS Network - mDNSResponder Section

- docs/getting-started/installation.md
- versioned_docs/version-1.11/getting-started/installation.md
- versioned_docs/version-latest/getting-started/installation.md
Updating URL list with documentation link as the help menu and help buttons make use of the link. Fixes #319
> Updating Proxy URLs - Docs URL

- docs/how-to-guides/mirror-private-registry.md
- sidebars.js
Adding a how-to guide for mirroring private registries in Rancher Desktop via provisioning script or updating the registry file. This fixes #259.
> How-to Mirror Private Registry

- docs/ui/preferences/wsl/integrations.md
- docs/ui/preferences/wsl/network.md
Adding in a warning section for the WSL Integrations page on symlinks being unsupported for RD versions 1.11.1 and later. Also removing the experimental flag for the Windows Network as it will be the default network in the 1.12 release.
Fixes #322
> Update kubeconfig WSL Behavior

- package.json
- yarn.lock
Updating the Docusaurus version to 3.0.1 to resolve dependency warnings and update relevant dependency fields in the yarn.lock file.
> Updating to Docusaurus V3.0.1 - Resolve Dependency Warnings

- docs/getting-started/deployment.md
- sidebars.js
- versioned_sidebars/version-1.11-sidebars.json
- versioned_sidebars/version-latest-sidebars.json
Updating the Generating Deployment Profiles version sidebar as it fell out of sync and was not displaying the page properly. Also added information into the Deployment Profiles page in the Getting Started section about the new version field being added with 1.12
> Deployment Profile Update

- docs/ui/preferences/wsl/network.md
- versioned_docs/version-1.12/ui/preferences/wsl/network.md
- versioned_docs/version-latest/ui/preferences/wsl/network.md
On Windows, network tunnel is no longer experimental as of 1.12.
Reference: https://github.com/rancher-sandbox/rancher-desktop/pull/6136
> Preferences: WSL: Network tunnel is no longer experimental

- docs/getting-started/installation.md
The previous URL was pointing to the Github repo with the source code, and was not accessed at runtime.
> Fix the upgrade-responder URL

- docs/getting-started/deployment.md
Capitalized "Version" key does not work, which is hinted at by #6296 (though not super-clear), as well as elsewhere in this document where lowercase version is used with the `plutil` commands.
> Update deployment.md macOS "version" key lowercase

- versioned_docs/version-1.12/getting-started/deployment.md
- versioned_docs/version-latest/getting-started/deployment.md
Syncing the deployment page after update to the version key is applied.
Attached to https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/340
> Sync Deployment Page

- docs/getting-started/deployment.md
- docs/getting-started/introduction.md
- docs/how-to-guides/installing-uninstalling-extensions.md
- docs/ui/containers.md
- docs/ui/diagnostics.md
- docs/ui/extensions.md
- docs/ui/general.md
- docs/ui/images.md
- docs/ui/port-forwarding.md
- docs/ui/preferences/application/behavior.md
- docs/ui/preferences/application/environment.md
- docs/ui/preferences/application/general.md
- docs/ui/preferences/container-engine/allowed-images.md
- docs/ui/preferences/container-engine/general.md
- docs/ui/preferences/kubernetes.md
- docs/ui/preferences/virtual-machine/emulation.md
- docs/ui/preferences/virtual-machine/hardware.md
- docs/ui/preferences/virtual-machine/network.md
- docs/ui/preferences/virtual-machine/volumes.md
- docs/ui/preferences/wsl/integrations.md
- docs/ui/preferences/wsl/network.md
- docs/ui/preferences/wsl/proxy.md
- docs/ui/snapshots.md
- docs/ui/troubleshooting.md
Updating the documentation links to point to 1.13 S3 screenshot locations. ~The introduction screenshot is a placeholder image while I create the screenshot manually, however, the link will remain the same.~ Done
> Docs v1.13 Screenshot Update

- docusaurus.config.js
Updating the Algolia search API key as crawler is blocked currently from scraping the site with incorrect key.
> Update Algolia Crawler - Search API Key

- docusaurus.config.js
Updating the API Key from the public `rancherdesktop` Algolia key to the public `rancherdesktop` Crawler key after reaching out to Algolia support. This is aimed to unblock the crawler. Also found helpful configuration info here: https://ronamosa.io/docs/engineer/docusaurus-algolia-search/
> Update API Key to Crawler API Key

- docs/tutorials/working-with-webassembly.md
- versioned_docs/version-1.13/tutorials/working-with-webassembly.md
- versioned_docs/version-latest/tutorials/working-with-webassembly.md
Expanded the tutorial to start from a simple hello-world program, compile it to a Wasm module and then package and run as a container. I have tested the provided steps on Windows. The steps need to be tested on macOS and Linux as part of the PR review.
> Expanded Wasm tutorial to cover steps from code to Wasm to containers

- .github/workflows/deploy.yml
Updated the deploy GitHub action to use the example provided in the [Docusaurus documentation](https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions). The purpose of the PR is to use the official actions/deploy-pages@v4 action.
> Updated the deploy GitHub action

- docs/ui/preferences/wsl/integrations.md
Starting with 1.13.0 the file became a symlink again.
This change should also be merged into the 1.13 branch of the docs.
Fixes #360
> Update WSL Integration info about ~/.kube/config

- versioned_docs/version-1.13/ui/preferences/wsl/integrations.md
> Applied changes made in PR-373 to version 1.13

- docs/how-to-guides/hello-world-example.md
- versioned_docs/version-1.15/how-to-guides/hello-world-example.md
Update the Dockerfile to copy only the index.html file instead of the entire directory.  While the performance impact is minimal for small files, this change aligns with  Docker best practices and prepares for potential future project growth. It also  serves as a reminder to be mindful of what we include in our Docker images.
> Refine Dockerfile to copy only index.html

- docs/references/rdctl-command-reference.md
- scripts/update-codeblocks
* Use `$` consistently for console blocks
* Strip user/os specific parts of rd-engine.json path
* Remove redundant <summary> lines
* Make more blocks autoupdate
Adding the `$` prefix makes it more complicated to cut & past commands, but I doubt anybody will do this frequently from the reference docs, and feel that consistency is more important.
Also fixes a bug in `update-codeblocks` where trailing newlines from command output could leak into the top of the following block.
> Update rdctl reference

- docs/how-to-guides/running-air-gapped.md
The bundled `k3s-versions.json` file generally makes is unneccessary to bundle a custom version unless the user also includes very recent k3s releases not yet included. Even then downloading the latest version from GitHub is the easiest way; it gets updated daily via GHA.
Once https://github.com/rancher-sandbox/rancher-desktop/issues/8003 is implemented we can get rid of these instructions completely.
Commit also updates some sample k3s versions because v1.19 is no longer supported.
Fixes #403
> Update k3s-versions.json info in airgap install instructions

- docs/tutorials/using-persistent-storage.md
When using pwsh (PowerShell 7.x), variable expansion doesn't seem to happen in the middle of arguments unless they're within double quotes.  Except that they do get expanded when checking with `echo`.
See: https://github.com/rancher-sandbox/rancher-desktop/issues/6900
(I think the user has _different_ problems, but the issue here was a red herring.)
> Tutorials: Storage: Quote arguments for PowerShell

- .github/workflows/test-deploy.yml
- .remarkrc.yaml
- Update NodeJS to current LTS version (whatever that is)
- Update GitHub Actions (checkout v3 → v4, setup-node v3 → v4)
- Move remark configuration to a YAML file so we can have comments and can read the expression easier
- Add the AppImage download location to ignored URLs, because sometimes we end up on a mirror with the file missing.  This should be fine because we check the file as one of the steps of our release check list.
This is in preparation for adding the URL from #708 that keeps failing for unknown reasons (but I wanted to do that in that PR instead of this one).
> Clean up CI test deployment workflow

- .remarkrc.yaml
Both openai and openwebui have their websites behind CloudFlare; this means that the link checker will fail in CI because it is detected as scraping.  Skip them (but not docs.openwebui) because they otherwise fail.
This is a follow-up to #423 where I actually test what fails and remove the things that don't matter.
> CI: Document dead url skip patterns

- docs/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.10/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.11/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.12/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.13/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.14/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.15/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.16/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.17/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.18/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.6/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.7/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.8/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.9-tech-preview/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-1.9/how-to-guides/setup-NGINX-Ingress-Controller.md
- versioned_docs/version-latest/how-to-guides/setup-NGINX-Ingress-Controller.md
The localdev.me seems to no longer work. localtest.me has been in operation since 2012, so hopefully will continue to be maintained.
Ref [Scott Forsyth's Blog - Introducing Testing Domain - localtest.me](https://asp-blogs.azurewebsites.net/owscott/introducing-testing-domain-localtest-me)
Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/8656
> Change localdev.me to localtest.me

- versioned_docs/version-1.10/ui/preferences/virtual-machine/network.md
- versioned_docs/version-1.10/ui/preferences/wsl/network.md
- versioned_docs/version-1.11/ui/preferences/virtual-machine/network.md
- versioned_docs/version-1.11/ui/preferences/wsl/network.md
- versioned_docs/version-1.12/ui/preferences/virtual-machine/network.md
- versioned_docs/version-1.12/ui/preferences/wsl/network.md
- versioned_docs/version-1.13/ui/preferences/virtual-machine/network.md
- versioned_docs/version-1.13/ui/preferences/wsl/network.md
- versioned_docs/version-1.14/ui/preferences/virtual-machine/network.md
- versioned_docs/version-1.14/ui/preferences/wsl/network.md
```shell
find versioned_docs -name 'network.md' -exec perl -n -i -e 'print unless m#canonical.*/network"#' {} \;
```
The `network.md` files were removed in #435.
All to appease the mighty link checker.
> Remove links to no longer existing network preferences

- docs/ui/containers.md
- containers are grouped by pod, docker-compose, or standalone
- table is updated automatically as containers come and go
- new container log option in the "meatball" menu
- container logs update automatically and are searchable
Closes https://github.com/rancher-sandbox/rancher-desktop/issues/9010
> Update Containers page documentation

- docs/tutorials/working-with-webassembly.md
As of RD 1.21, we are preferring the containerd image store when using the moby backend.  All new VMs are created using that store, and once that is enabled we never switch back.
Fixes #454 (the release-note label was added to https://github.com/rancher-sandbox/rancher-desktop/issues/9123)
> Tutorials: Wasm: Update note about image store
